development:
  adapter: postgresql
  encoding: unicode
  database: ketten_development
  pool: 5
  username: cschep
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ketten_test
  pool: 5
  username: cschep
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ketten_production
  pool: 5
  host: localhost
  username: ketten_postgresql_user
  password: XXXXX_SUPER_SECURE_PASS_XXXXX
