---
- hosts: all
  become: true
  vars_files:
    - app-vars.yml

  roles:
    - role: ssh
    - role: ruby
      tags: ruby
    - role: nodejs
      tags: nodejs
    - role: yarn
      tags: nodejs
    - role: postgresql
      tags: postgresql
  # - role: redis
  #   tags: redis
    - role: nginx
      tags: nginx
    - role: certbot
      tags: certbot
    - role: ufw
      tags: ufw
  # - role: logrotate
  #   tags: logrotate

