---
# - name: add univere repo ?
#   apt_repository:
#     repo: universe

- name: install nginx
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    force: yes
    update_cache: yes

# - name: Create certbot directory
#   file: path=/opt/certbot state=directory mode=0755 owner=root group=root

# - name: Install certbot standalone
#   get_url:
#     url: "{{ certbot_url }}"
#     dest: "{{ certbot_dir }}/certbot-auto"

# - name: Ensure that certbot-auto is executable
#   file:
#     path: "{{ certbot_dir }}/certbot-auto"
#     mode: 0755

- name: Ensure that nginx is stopped
  service:
    name: nginx
    state: stopped

- name: Check & get new certificate
  include_tasks: cert.yml
  loop: "{{ certbot_domains }}"
  loop_control:
    loop_var: domain

- name: Add certbot renewal cronjob
  cron: name="renew letsencrypt certificates" hour="0" minute="0" job="certbot renew --non-interactive --quiet --standalone --pre-hook 'service nginx stop' --post-hook 'service nginx start'"